version: '3.8'

networks:
  traefik:
    external:
      name: traefik

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: always
    security_opt:
      - no-new-privileges:true

    command:
      - --api=true
      - --api.dashboard=true

      - --log=true
      - --log.level=DEBUG

      - --accessLog=true
      - --accessLog.filePath=/traefik.log
      - --accessLog.bufferingSize=100
      - --accessLog.filters.statusCodes=400-499

      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure

      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.middlewares=secureHeaders@file,rate-limit@file
      - --entrypoints.websecure.http.tls.certResolver=letsencrypt

      - --providers.docker=true
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.exposedbydefault=false
      - --providers.file.directory=/configurations
      - --providers.file.watch=true

      - --providers.docker.network=traefik

#      - --certificatesresolvers.letsencrypt.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.letsencrypt.acme.caServer=https://acme-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.letsencrypt.acme.email=vdarkobar@gmail.com
      - --certificatesresolvers.letsencrypt.acme.storage=/acme.json
      - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.resolvers[0]=1.1.1.1:53
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.resolvers[1]=1.0.0.1:53
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.delaybeforecheck=0

#      - --entrypoints.websecure.http.tls.domains[0].main=home-network.me
#      - --entrypoints.websecure.http.tls.domains[0].sans=*.home-network.me

      - --entrypoints.websecure.http.tls.options=default

    ports:
      - 80:80
      - 443:443

    environment:
      - CF_API_EMAIL=vdarkobar@gmail.com
      - CF_API_KEY=52c388be9f67a76e3abf31c10c175a6e96db2

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/acme.json:/acme.json
      - ./traefik.log:/traefik.log
      # Add folder with dynamic configuration yml
      - ./data/configurations:/configurations

    networks:
      - traefik

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.traefik-secure.entrypoints=websecure"
      - "traefik.http.routers.traefik-secure.rule=Host(`proxy.home-network.me`)"
      - "traefik.http.routers.traefik-secure.middlewares=user-auth@file"
      - "traefik.http.routers.traefik-secure.service=api@internal"
  
